# site_name: PyCharm User Guide
# theme:
#   name: material
#   features:
#     - navigation.tabs
#     - navigation.sections
#     - toc.integrate
#     - navigation.top
#     - search.suggest
#     - search.highlight
#     - content.tabs.link
#     - content.code.annotation
#     - content.code.copy
#   language: en
#   palette: 
#     - scheme: default 
#       toggle:
#         icon: material/toggle-switch-off-outline
#         name: Switch to dark mode
#       primary: teal
#       accent: purple
#     - scheme: slate 
#       toggle:
#         icon: material/toggle-switch
#         name: Switch to light mode
#       primary: teal
#       accent: lime







# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippers
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
#   - pymdownx.emoji: 
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

# extra: 
#   social:
#     - icon: fontawsome/brands/github-alt
#       link: https://github.com
#     - icon: fontawsome/brands/twitter
#       link: https://twitter.com
#     - icon: fontawsome/brands/linkedin
#       link: https://www.linkedin.com

# copyright:
#   &copy: 2023 <a href="https://github.com" target="_blank" rel="noopener"> GitHub </a>

    


site_name: PyCharm User Guide

theme:
  name: material
  features: content.code.copy



  palette:

 # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


markdown_extensions:
  - attr_list
  - md_in_html


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

